### ISSUE TITLE
global binding fails on ubuntu 17.x

### ISSUE THREAD

**Issue by coryrylan** [vintage-software/arbor#32]
![screenshot from 2017-11-27 15-17-31](https://user-images.githubusercontent.com/2021067/33289737-24700ce4-d386-11e7-8cd2-9a8b2f401098.png)

**Comment by kevinphelps** [comment]
Ugh.

**Comment by coryrylan** [comment]
I'll see if I can debug it this week

**Comment by coryrylan** [comment]
![arbor](https://user-images.githubusercontent.com/2021067/35703694-a2f4a736-0762-11e8-9a21-65224972cd4d.png)

Works now :)
